### ISSUE TITLE
Cannot correctly set the filter condition of the CSI data packet of device B

### ISSUE THREAD

**Issue by NJUPT-Sivan** [espressif/esp-csi#46] opened 2022-03-27 13:26 UTC
![picture of console_test-sta](https://gitee.com/Xu--Siyuan/image-bed/raw/master/image/%E5%B1%8F%E5%B9%95%E6%88%AA%E5%9B%BE%20.png)
> when I try the fifith step of console_test, what is to Set the filter condition of the CSI data packet of device B, the size of the CSI data packet is: 384, and the filtered device is: MAC address of device A(AP mode).    I meet a problem ,as the picture shows ,could you tell me how to solve this problem? Thanks a lot!

**Comment by zhanzhaocheng** [comment] 2022-03-30 06:12
This is caused by the error of command line input parsing. You can try it and write the command and code directly. For usage, see: https://github.com/espressif/esp-csi/issues/41

**Comment by zhanzhaocheng** [comment] 2023-05-31 06:10
Hello, @NJUPT-Sivan 

Closing this issue, feel free to reopen with more updates. Thanks.

**Closed by zhanzhaocheng** 2023-05-31 06:10 UTC
