### ISSUE TITLE
the csi gui tool is not showing any csi graph (AEGHB-315)

### ISSUE THREAD

**Issue by roycesteven** [espressif/esp-csi#128] opened 2023-07-23 07:46 UTC
<img width="1280" alt="Screenshot 2023-07-23 144806" src="https://github.com/espressif/esp-csi/assets/86450052/a497cdcb-4ce0-41aa-811d-58bc067c7a00">

**Comment by MacChu0315-Espressif** [comment] 2023-07-27 11:58
I apologize for the inconvenience caused, but we were unable to reproduce the issue you mentioned. Could you please provide more detailed logs for our reference? Additionally, it seems that you are using an older version. You may consider trying the latest version and then attempt the process again.

Kindly provide us with more information or logs so that we can better assist you in resolving the problem. Thank you for your cooperation and understanding.

**Comment by zhanzhaocheng** [comment] 2023-09-18 11:25
Hello, @roycesteven 

Closing this issue, feel free to reopen with more updates. Thanks.

**Closed by zhanzhaocheng** 2023-09-18 11:25 UTC
